steps:
- name: 'docker.io/library/python:3.9'
  entrypoint: /bin/sh
  # Run pip install and pytest in the same build step
  # (pip packages won't be preserved in future steps!)
  args: [-c, 'pip install -r requirements.txt && pytest']
  dir: '/Users/pyatiluk/Desktop/python'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'get_tweets_ikea', '--trigger-topic ikea', '--runtime', 'python39', '--entry-point', 'get_tweets_ikea']
  dir: '/Users/pyatiluk/Desktop/python/app'
